#!/bin/bash                                                                                                                                                                                                                                             
STATE_FILE="/tmp/rofi-calendar-state"                                                                                                                                                                                                                   
                                                                                                                                                                                                                                                      
if [ ! -f "$STATE_FILE" ]; then                                                                                                                                                                                                                         
  echo "$(date +%Y) $(date +%m)" > "$STATE_FILE"                                                                                                                                                                                                      
fi                                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                      
read YEAR MONTH < "$STATE_FILE"                                                                                                                                                                                                                         
                                                                                                                                                                                                                                                      
show_calendar() {                                                                                                                                                                                                                                       
  echo "$(cal --color=always -m "$MONTH" "$YEAR" | sed 's/^/  /')"                                                                                                                                                                                    
  echo "---"                                                                                                                                                                                                                                          
  printf "   Today    󰁍 Prev    󰁕 Next"                                                                                                                                                                                                              
}                                                                                                                                                                                                                                                       
                                                                                                                                                                                                                                                      
if [ $# -eq 0 ]; then                                                                                                                                                                                                                                   
  show_calendar                                                                                                                                                                                                                                       
else                                                                                                                                                                                                                                                    
  case "$1" in                                                                                                                                                                                                                                        
      *"Prev"*)                                                                                                                                                                                                                                       
          [ "$MONTH" -eq 1 ] && echo "$((YEAR - 1)) 12" > "$STATE_FILE" \                                                                                                                                                                             
              || echo "$YEAR $((10#$MONTH - 1))" > "$STATE_FILE"                                                                                                                                                                                      
          read YEAR MONTH < "$STATE_FILE"; show_calendar ;;                                                                                                                                                                                           
      *"Next"*)                                                                                                                                                                                                                                       
          [ "$MONTH" -eq 12 ] && echo "$((YEAR + 1)) 1" > "$STATE_FILE" \                                                                                                                                                                             
              || echo "$YEAR $((10#$MONTH + 1))" > "$STATE_FILE"                                                                                                                                                                                      
          read YEAR MONTH < "$STATE_FILE"; show_calendar ;;                                                                                                                                                                                           
      *"Today"*)                                                                                                                                                                                                                                      
          echo "$(date +%Y) $(date +%m)" > "$STATE_FILE"                                                                                                                                                                                              
          read YEAR MONTH < "$STATE_FILE"; show_calendar ;;                                                                                                                                                                                           
      *) exit 0 ;;                                                                                                                                                                                                                                    
  esac                                                                                                                                                                                                                                                
fi  
